dertitle: Marvin Krauspenhaar
description: mathematician and programmer
first_name: Marvin
last_name: Krauspenhaar

url: marvin-sh.github.io

show_downloads: false
google_analytics:
theme: jekyll-theme-slate
