title: Marvin's Portfolio
description: Welcome to my Gamedev Portfolio. Below I've listed some projects I have worked on.
first_name: Marvin
last_name: Krauspenhaar

url: marvin-sh.github.io

show_downloads: false
google_analytics:
theme: jekyll-theme-slate
