title: Marvin Portfolio
description: Welcome to my Gamedev Portfolio. I've listed some projects I was part of below.
first_name: Marvin
last_name: Krauspenhaar

url: marvin-sh.github.io

show_downloads: false
google_analytics:
theme: jekyll-theme-slate
